version: 2
jobs:
  test_frontend:
    working_directory: ~/photobank
    docker:
      - image: node:6.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - frontend-node_modules-{{ checksum "frontend/package.json" }}

      - restore_cache:
          keys:
          - frontend-elm-stuff-{{ checksum "frontend/elm-package.json" }}

      #
      # https://github.com/elm-lang/elm-compiler/issues/1473
      #
      - restore_cache:
          keys:
          - sysconfcpus
      - run: |
          if [ ! -d ~/sysconfcpus/bin ]
          then
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git clone https://github.com/obmarg/libsysconfcpus.git
            cd libsysconfcpus
            ./configure --prefix="$HOME/sysconfcpus"
            make && make install
          fi
      - save_cache:
          paths:
            - ~/sysconfcpus
          key: sysconfcpus

      - run: |
          cd frontend
          npm install
          # Remove once the global Elm dep is removed
          # https://github.com/tcoopman/elm-css-webpack-loader/issues/20
          npm install -g elm

      - save_cache:
          key: frontend-elm-stuff-{{ checksum "frontend/elm-package.json" }}
          paths:
            - frontend/elm-stuff

      - save_cache:
          key: frontend-node_modules-{{ checksum "frontend/package.json" }}
          paths:
            - frontend/node_modules

      - run: |
          cd frontend
          ~/sysconfcpus/bin/sysconfcpus -n 2 make build

      - run: |
          cd frontend
          ~/sysconfcpus/bin/sysconfcpus -n 2 make test-once


  test_backend:
    working_directory: ~/photobank
    docker:
      - image: ruby:2.4.1-alpine
      # - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - type: cache-restore
        key: rails-demo-{{ checksum "backend/Gemfile.lock" }}

      - run: cd backend && bundle install --path vendor/bundle

      - type: cache-save
        key: rails-demo-{{ checksum "backend/Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: shell
        command: cd backend && ./bin/run_tests.rb

      - type: shell
        command: cd backend && rubocop -D .


workflows:
  version: 2
  all:
    jobs:
      - test_frontend
      - test_backend
