version: 2
jobs:
  test_frontend:
    working_directory: ~/photobank
    docker:
      - image: node:6.11.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
          - frontend-node_modules-{{ checksum "frontend/package.json" }}

      - restore_cache:
          keys:
          - frontend-elm-stuff-{{ checksum "frontend/elm-package.json" }}

      #
      # https://github.com/elm-lang/elm-compiler/issues/1473
      #
      - restore_cache:
          keys:
          - sysconfcpus
      - run: |
          if [ ! -d ~/sysconfcpus/bin ]
          then
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git clone https://github.com/obmarg/libsysconfcpus.git
            cd libsysconfcpus
            ./configure --prefix="$HOME/sysconfcpus"
            make && make install
          fi
      - save_cache:
          paths:
            - ~/sysconfcpus
          key: sysconfcpus

      - run: |
          cd frontend
          npm install
          # Remove once the global Elm dep is removed
          # https://github.com/tcoopman/elm-css-webpack-loader/issues/20
          npm install -g elm

      - save_cache:
          key: frontend-elm-stuff-{{ checksum "frontend/elm-package.json" }}
          paths:
            - frontend/elm-stuff

      - save_cache:
          key: frontend-node_modules-{{ checksum "frontend/package.json" }}
          paths:
            - frontend/node_modules

      - run: |
          cd frontend
          ~/sysconfcpus/bin/sysconfcpus -n 2 make build

      - run: |
          cd frontend
          ~/sysconfcpus/bin/sysconfcpus -n 2 make test-once

      - persist_to_workspace:
          root: .
          paths:
            - frontend/dist/*


  test_backend_ruby:
    working_directory: ~/photobank
    docker:
      - image: ruby:2.4.1-alpine
      # - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - type: cache-restore
        key: backend-ruby-{{ checksum "backend-ruby/Gemfile.lock" }}

      - run: cd backend-ruby && bundle install --path vendor/bundle

      - type: cache-save
        key: backend-ruby-{{ checksum "backend-ruby/Gemfile.lock" }}
        paths:
          - backend-ruby/vendor/bundle

      - type: shell
        command: cd backend-ruby && ./bin/run_tests.rb

      - type: shell
        command: cd backend-ruby && rubocop -D .

  test_backend_elixir:
    working_directory: ~/photobank
    docker:
      - image: bitwalker/alpine-elixir:1.5.0
      - image: circleci/postgres:9.4.12-alpine
    environment:
      - MIX_ENV: test
    steps:
      - checkout
      - run: cd backend-elixir && cp mix.lock mix.lock.bak

      # Restore cache
      - run: apk add --update tar
      - restore_cache:
          key: backend-elixir-{{ checksum "backend-elixir/mix.lock.bak" }}

      # Install deps
      - run: cd backend-elixir && mix local.hex --force
      - run: cd backend-elixir && mix local.rebar --force
      - run: cd backend-elixir && mix deps.get
      - run: cd backend-elixir && mix deps.compile

      # Cache deps
      - run: cd backend-elixir && mix clean
      - save_cache:
          key: backend-elixir-{{ checksum "backend-elixir/mix.lock.bak" }}
          paths:
            - backend-elixir/deps
            - backend-elixir/_build

      - run: cd backend-elixir && mix compile --warnings-as-errors
      - run: cd backend-elixir && mix test

  build_docker_elixir:
    working_directory: ~/photobank
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --update docker git ca-certificates
      - run: update-ca-certificates
      - attach_workspace:
          at: /tmp/workspace
      - run: ./bin/ci-docker-image-build-push.sh

workflows:
  version: 2
  all:
    jobs:
      - test_frontend
      - test_backend_ruby
      - test_backend_elixir
      - build_docker_elixir:
          requires:
            - test_frontend
            - test_backend_elixir
          filters:
            branches:
              only: /^master$/
