version: 2
jobs:
  build:
    working_directory: ~/bank
    docker:
      - image: node:6.11.1
    steps:
      - checkout

      #
      # Deps cache
      #

      - restore_cache:
          keys:
          - frontend-node_modules-{{ checksum "frontend/package.json" }}

      - restore_cache:
          keys:
          - frontend-elm-stuff-{{ checksum "frontend/elm-package.json" }}

      - restore_cache:
          keys:
          - backend-node_modules-{{ checksum "backend/package.json" }}


      #
      # https://github.com/elm-lang/elm-compiler/issues/1473
      #
      - restore_cache:
          keys:
          - sysconfcpus
      - run: |
          if [ ! -d ~/sysconfcpus/bin ]
          then
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git clone https://github.com/obmarg/libsysconfcpus.git
            cd libsysconfcpus
            ./configure --prefix="$HOME/sysconfcpus"
            make && make install
          fi
      - save_cache:
          paths:
            - ~/sysconfcpus
          key: sysconfcpus


      #
      # Backend
      #

      - run: |
          cd backend
          npm install

      - save_cache:
          paths:
            - backend/node_modules
          key: backend-node_modules-{{ checksum "backend/package.json" }}

      - run: |
          cd backend
          make test-once


      #
      # Frontend
      #

      - run: |
          cd frontend
          npm install

      - save_cache:
          paths:
            - frontend/elm-stuff
          key: frontend-elm-stuff-{{ checksum "frontend/elm-package.json" }}

      - run: |
          cd frontend
          ~/sysconfcpus/bin/sysconfcpus -n 2 make build

      - run: |
          cd frontend
          ~/sysconfcpus/bin/sysconfcpus -n 2 make test-once
