AllCops:
  Exclude:
    - "vendor/**/*"

Metrics/LineLength:
  Max: 80

Documentation:
  Enabled: false

# Method length is a poor complexity metric, use others.
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

# Trailing commas reduce diff noise
Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

# Allow use of empty lines to visually group code into 'paragraphs'
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# https://viget.com/extend/just-use-double-quoted-ruby-strings
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/StringLiteralsInInterpolation:
  EnforcedStyle: "double_quotes"
